language: cpp
os: linux
dist: trusty
compiler:
  - gcc
  - clang

before_install:
  - test -n $CC && unset CC

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
  - ./test_c
  - ./test_cxx
