language: cpp
os: linux
# dist: trusty
compiler:
  - gcc
  - clang

before_install:
  - test -n $CC && unset CC

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgomp1
      - gcc-6
      - clang-6

script:
  - export
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
  - make test
  - ./test_c
  - ./test_cxx
